### ISSUE TITLE
When releasing a component, if building fails, it says nothing

### ISSUE THREAD

**Issue by miduga** [SUI-Components/SUIStudio#59]
Doing a `suistudio release` if the component building fails, it doesn't show you an error message.

Version: 3.4.0

**Comment by naxhh** [comment]
If I'm not wrong this is fixed with crm/sui-mono 

I think I've tested this one but not sure right now...

If anyone wants to PR it in the meantime the idea was to use parent stdout and stderr for the spawn commands.

See: https://github.com/SUI-Components/commit-release-manager/blob/master/crm/bin/crm-release.js#L37
and https://github.com/SUI-Components/commit-release-manager/blob/master/crm/src/execute.js#L28

**Comment by davidbarna** [comment]
Solved in sui-studio@4, as commands are now spawned.
